<?php

namespace Extensions\Plugins\Support_alfiory__930442654\App\Models;

use Geeky\Database\CacheQueryBuilder;
use Illuminate\Database\Eloquent\Model;

class SupportAlfiorySetting extends Model
{
    use CacheQueryBuilder;

    protected $table = 'support_alfiory__settings';
    protected $fillable = ['sentences', 'enable_priority_support', 'priority_support_articles'];

    public function create(array $attributes = [])
    {
        return parent::create($attributes); // TODO: Change the autogenerated stub
    }
}
