<?php

namespace Extensions\Plugins\Support_alfiory__930442654\App\Models;

use Geeky\Database\CacheQueryBuilder;
use Illuminate\Database\Eloquent\Model;

class SupportAlfioryTicketsMessage extends Model
{
    use CacheQueryBuilder;

    protected $table = 'support_alfiory__tickets_messages';

    protected $fillable = ['seen', 'updated_at'];

    public function create(array $attributes = [])
    {
        return parent::create($attributes); // TODO: Change the autogenerated stub
    }
}
