<?php

namespace Extensions\Plugins\Support_alfiory__930442654\App\Models;

use Geeky\Database\CacheQueryBuilder;
use Illuminate\Database\Eloquent\Model;

class SupportAlfioryTicket extends Model
{
    use CacheQueryBuilder;

    protected $table = 'support_alfiory__tickets';

    protected $fillable = ['resolved', 'tags', 'updated_at'];

    public function create(array $attributes = [])
    {
        return parent::create($attributes); // TODO: Change the autogenerated stub
    }
}
